### ISSUE TITLE
[META] repo ideas

### ISSUE THREAD

**Issue by moul** [gnolang/old-getting-started-workshop#2]
## Foundations

* [x] configure gitpod (#1)
* [x] reference on awesome-gno (https://github.com/gnolang/awesome-gno/pull/43)
* [x] share ownership between coreteam and devrels (#4)
* [x] readme should explain the goals (workshop content, later=gno ide, can be useful for fork) (#3, #9)
* [x] learn to run/test a contract with `gno` (#5)
* [x] Makefile with convenient commands (#6)
* [x] reference from gnolang/workshops repo (https://github.com/gnolang/workshops/tree/main/presentations/2023-07-23--workshop-nebular--manfred-morgan)

## Suggested Curriculum V1

- [x] 1. Explore the Gno CLI and learn how to write contracts without relying on the blockchain. (#5)
- [x] 2. Master the usage of gnokey for efficient account management and performing transactions. (#12) 
- [x] 3. Gain proficiency in debugging and completing contracts. (#14)
- [x] 4. Publish your contracts on a devnet and various testnets for thorough testing. (#13)
- [ ] 5. Bonus: Create a microblog/forum/foobar application with multiple contracts.

## Bonuses

* [x] configure vscode (#10)
* [ ] setup CI/CD, especially for people who fork the repo
* [ ] reduce boilerplate to make the repo as clean as possible, especially the root dir
* [ ] replicate / set up sync if it makes sense with the main repo, I.e the gitpod.yml file, or the .gno files (to have single source of truth + CI)
